##########################################     Login Page Elements     #################################################
txt_username="id:username"
txt_password="id=password"
btn_connexion="id:kc-login"

#########################################    Rules Page Elements    ####################################################
menu_regles="xpath://*[@id=\"orange-navbar-collapse\"]/ul/li[2]/a/span/span"

flt_nom_regle="xpath=//*[@id=\"filtre\"]/div[1]"
flt_descprition_regle="xpath=//*[@id=\"filtre\"]/div[2]/angular2-multiselect/div/div[1]/div"
flt_severite_regle="xpath=//*[@id=\"filtre\"]/div[3]/angular2-multiselect/div/div[1]/div"
flt_date_modif_regle="xpath=//*[@id=\"dropdownImpact\"]/span[1]"
flt_scope_regle="xpath=//*[@id=\"filtre\"]/div[5]/angular2-multiselect/div/div[1]/div"
flt_statut_regle="xpath=//*[@id=\"filtre\"]/div[6]/angular2-multiselect/div/div[1]/div"

col_nom_regle="xpath://*[@id=\"regles_tab_info\"]/thead/tr/th[2]"
col_description_regle="xpath://*[@id=\"regles_tab_info\"]/thead/tr/th[3]"
col_severite_regle="xpath://*[@id=\"regles_tab_info\"]/thead/tr/th[4]"
col_frequence_regle="xpath://*[@id=\"regles_tab_info\"]/thead/tr/th[5]"
col_date_creation_regle="xpath://*[@id=\"regles_tab_info\"]/thead/tr/th[6]"
col_date_modif="xpath://*[@id=\"regles_tab_info\"]/thead/tr/th[7]"
col_scope_regle="xpath://*[@id=\"regles_tab_info\"]/thead/tr/th[8]"
col_statut_regle="xpath://*[@id=\"regles_tab_info\"]/thead/tr/th[9]"

btn_create_new_regle="xpath:/html/body/jhi-main/div[2]/div/div/jhi-regle/div/div[1]/div/div/div/a/span/span"

btn_activer_desactiver="xpath://*[@id=\"regles_tab_info\"]/tbody/tr[1]/td[10]/div/div/label"
#Page creation regle
txt_name="id:name"
txt_name_description="id:field_description"
txt_network="id:field_network"
txt_severite="id:field_severity"
txt_freq_quotidien= "link=Quotidien"
txt_quotidien_heure= "//div[@id='step1']/div/div/div/div[5]/cron-editor/div/div/div/div/div/div[3]/div/cron-time-picker/select"
txt_window="xpath://*[@id=\"field_window\"]"
txt_windowSelectedType="id:field_windowSelectedType"
txt_scope="id:field_scope"
txt_flux="id:field_flux"
txt_operator="id:field_operator"
txt_typeRegle="id:field_ruleType"
txt_filtre="//angular2-multiselect[@id='field_filters']/div/div/div"
txt_search_Filtre="xpath=(//input[@type='text'])[4]"
btn_add_filtre="//div[@id='step1']/div/div[2]/div/div[5]/div[2]/a/mat-icon"
filtre_champ_datastream="//span/div/div/select" #"/html/body/ngb-modal-window/div/div/jhi-filter-dialog/form/div[2]/span/div[1]/div/select"
filtre_operator="//span/div[2]/div/select"
filtre_valeur="xpath=(//input[@type='text'])[21]"
filtre_icone_add="//div[5]/div/a/i"
filtre_OPERATION = "//span/div[4]/div/select"
filtre_champ_datastream_2="//span[2]/div/div/select"
filtre_operator_2="//span[2]/div[2]/div/select"
filtre_valeur_2="xpath=(//input[@type='text'])[22]"
filtre_icone_add_2="//span[2]/div[5]/div/a/i"
filtre_OPERATION_2 = "//span[2]/div[4]/div/select"
filtre_champ_datastream_3="//span[3]/div/div/select"
filtre_operator_3="//span[3]/div[2]/div/select"
filtre_valeur_3="xpath=(//input[@type='text'])[23]"
filtre_icone_add_3="//span[3]/div[5]/div/a/i"
filtre_OPERATION_3 = "//span[3]/div[4]/div/select"
filtre_champ_datastream_4="//span[4]/div/div/select"
filtre_operator_4="//span[4]/div[2]/div/select"
filtre_valeur_4="xpath=(//input[@type='text'])[24]"
filtre_icone_add_4="//span[4]/div[5]/div/a/i"
filtre_OPERATION_4 = "//span[4]/div[4]/div/select"
filtre_champ_datastream_5="//span[5]/div/div/select"
filtre_operator_5="//span[5]/div[2]/div/select"
filtre_valeur_5="xpath=(//input[@type='text'])[25]"
btn_ajouter_filtre="//div[4]/div/button/span"
txt_libelle_filtre="id=libelle"
btn_sauvegarder_filtre="//div[@id='save']/button[2]"
txt_monitor="id:field_monitor"
txt_fonction="id:field_fonction"
txt_threshold="xpath://*[@id=\"field_threshold\"]"
txt_field_thresholdUnit="id:field_thresholdUnit"
txt_field_thresholdFrequency="id:field_thresholdFrequency"
txt_field_offreFormule="id:field_offreFormule"
btn_suivant="xpath://*[@id=\"form-add-rule\"]/div/div[2]/button[2]/span/span"
txt_analyste_action="xpath://*[@id=\"form-add-rule\"]/div/div[2]/button[3]/span/span"
verif_regle="xpath://*[@id=\"regles_tab_info\"]/tbody/tr[1]/td[2]"


########################################        Alertes Page Elements       ############################################
clic_menu_alertes="xpath=//*[@id=\"orange-navbar-collapse\"]/ul/li[3]/a/span/span"
clic_alerte="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alerte/div/div[3]/div/div/div/div/table/tbody/tr[1]/td[2]"
col_cle="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alerte/div/div/div/div[2]/jhi-alertes-list/div/div/div/div/div/div/table/thead/tr/th[2]/span/span"
#col_nomAlerte="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alerte/div/div[3]/div/div/div/div/table/thead/tr/th[3]/span/span"
col_nomAlerte="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[3]/span/span"
#col_reseau="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alerte/div/div[3]/div/div/div/div/table/thead/tr/th[4]/span/span"
col_reseau="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[4]/span/span"
col_dateCreation="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[5]/span/span"
#col_dateCreation="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alerte/div/div[3]/div/div/div/div/table/thead/tr/th[5]/span/span"
col_typeAggregation="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[6]/span/span"
#col_typeAggregation="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alerte/div/div[3]/div/div/div/div/table/thead/tr/th[6]/span/span"
col_valeurAggregation="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[7]/span/span"
#col_valeurAggregation="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alerte/div/div[3]/div/div/div/div/table/thead/tr/th[7]/span/span"
col_regle="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[8]/span/span"
#col_regle="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alerte/div/div[3]/div/div/div/div/table/thead/tr/th[8]/span/span"

ligne_table_alerte="//td[2]"
valueOf_nbr_Enregistrement="xpath=//tr[5]/td"
#valueOf_nbr_CDR="xpath=//*[@id=\"tab-1-content\"]/div[2]/table/tbody"
valueOf_nbr_CDR="xpath=//*[@id=\"tab-1-content\"]/div[2]/table/tbody/tr/td[5]"

txt_nom_alerte="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alerte-detail/div/div/div[1]/div/div/div[1]/h1"

######################################       Alarmes Page Elements      ################################################
menu_alarmes="xpath://*[@id=\"alarmsNavBarDropdown\"]/span/span"
sous_menu_alarmes="xpath://*[@id=\"orange-navbar-collapse\"]/ul/li[4]/ul/li[1]/a/span/span"
#sous_menu_alarmesSimbox="xpath=//*[@id=\"orange-navbar-collapse\"]/ul/li[4]/ul/li[2]/a/span/span"
sous_menu_alarmesSimbox="xpath=//*[@id=\"orange-navbar-collapse\"]/ul/li[4]/ul/li[3]/a/span/span"
sous_menu_alarmesSMSA2P="xpath=//*[@id=\"orange-navbar-collapse\"]/ul/li[4]/ul/li[5]/a/span/span"
sous_menu_allAlarmes="xpath=//*[@id=\"allAlarmes\"]/a/span"
sous_menu_myAlarmes="xpath=//*[@id=\"myAlarmes\"]/a/span"
sous_menu_closedAlarms="xpath=//*[@id=\"closedAlarms\"]/a/span"
survoler_statutAlarme="xpath = //*[@id=\"table-alarm\"]/tbody/tr[1]/td[11]/div[1]"

flt_regle="xpath=//*[@id=\"filtre\"]/div[1]/div[1]/angular2-multiselect/div/div[1]/div"
flt_dateCreation="//*[@id=\"dropdownImpact\"]/span"
flt_valorisation="//*[@id=\"dropdownImpact\"]/span[1]/span"
flt_assignation="//*[@id=\"filtre\"]/div[1]/div[5]/angular2-multiselect/div/div[1]/div/span[1]"
flt_nbrAlertes="//*[@id=\"dropdownAlertCount\"]/span[1]/span"
flt_statutAlarme="//*[@id=\"filtre\"]/div[1]/div[7]/angular2-multiselect/div/div[1]/div/span[1]"
flt_statutAlarme_Simbox="//*[@id=\"filtre\"]/div[1]/div[8]/angular2-multiselect/div/div[1]/div/span[1]"
flt_typeAlarme="//*[@id=\"filtre\"]/div[1]/div[8]/angular2-multiselect/div/div[1]/div/div"
flt_dateModification="xpath=(//button[@id='dropdownImpact']/span)[3]"
flt_spread="//button[@id='dropdownSpread']/span/span"
flt_source="//form[@id='filtre']/div/div[7]/angular2-multiselect/div/div/div/span"

table_liste_alarme="//*[@id=\"table-alarm\"]/tbody"
ligne_50_alarme="//*[@id=\"table-alarm\"]/tbody/tr[50]"
ligne_45_alarme="//*[@id=\"table-alarm\"]/tbody/tr[45]"
ligne_47_alarme="//*[@id=\"table-alarm\"]/tbody/tr[47]"

col_nomAlarme="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[3]/span"
col_regleAlarme="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[4]/span"
col_dateCreationAlarme="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[5]/span"
col_dateModificationAlarme="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[6]/span"
col_valeurAggregationAlarme="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[7]/span"
col_valorisationAlarme="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[8]/span"
col_nbrAlertesAlarme="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[9]/span"
col_assignAlarme="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[10]/span"
col_statutAlarme="xpath=//*[@id=\"table-alarm\"]/thead/tr/th[11]/span"
col_valorisation_Alarmes="//table[@id='table-alarm']/thead/tr/th[7]/span"
col_spread_Alarme="//table[@id='table-alarm']/thead/tr/th[8]/span"
col_appelSortant_Alarme="//table[@id='table-alarm']/thead/tr/th[9]/span"
col_dureeAppel_Alarme="//table[@id='table-alarm']/thead/tr/th[10]/span"
col_source_Alarme="//table[@id='table-alarm']/thead/tr/th[11]/span"
col_assigneA_Alarme="//table[@id='table-alarm']/thead/tr/th[12]/span"
col_statut_Alarmes="//table[@id='table-alarm']/thead/tr/th[13]/span"

#search_statutAlarme="xpath=//*[@id=\"filtre\"]/div[1]/div[7]/angular2-multiselect/div/div[2]/div[3]/div[2]/input"
search_statutAlarme="xpath=(//input[@type='text'])[3]"
check_statutAlarme= "xpath=//*[@id=\"filtre\"]/div[1]/div[7]/angular2-multiselect/div/div[2]/div[3]/ul/span/li"
checked_first_alarme_in_the_list="xpath=//*[@id=\"table-alarm\"]/tbody/tr[1]/td[2]"
cheked_statutNEW="xpath=//*[@id=\"filtre\"]/div[1]/div[7]/angular2-multiselect/div/div[2]/div[3]/ul/span/li[1]"
cheked_statutINV="xpath=//*[@id=\"filtre\"]/div[1]/div[7]/angular2-multiselect/div/div[2]/div[3]/ul/span/li[2]"
first_alarme_in_the_list="xpath=//*[@id=\"table-alarm\"]/tbody/tr[1]/td[3]"

#clic_sur_une_alarme="xpath=//*[@id=\"table-alarm\"]/tbody/tr[2]/td[3]"
clic_sur_une_alarme="xpath=//*[@id=\"table-alarm\"]/tbody/tr[1]/td[3]"
clic_lien_voirPlus="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[3]/div[2]/div/a/span"

#btn_reset="xpath=//*[@id=\"serchToolButton\"]/a[1]"
btn_reset="xpath=//*[@id=\"serchToolButton\"]/a[1]"
btn_filter="xpath=//*[@id=\"serchToolButton\"]/a[2]"
btn_assignation="xpath = //*[@id=\"assigned-to\"]"
btn_action="xpath=//*[@id=\"dropdownManual\"]"
btn_export="//div[2]/a/span/span"
btn_options=" xpath=//*[@id=\"dropdownOptions\"]"
btn_search="xpath=//*[@id=\"orange-navbar-collapse\"]/ul/li[9]/div/li[1]/div/form/button"
btn_cloturer="xpath = /html/body/jhi-main/div[2]/div/div/jhi-alarm/div/div/div/div[1]/jhi-alarms-header/div[2]/div/form/div/div[3]/div/button/span"
btn_noFraud="xpath = /html/body/ngb-modal-window/div/div/jhi-alarm-popup/form/div[3]/button[3]/span[2]/span"
btn_voir_alerte="//button[@type='submit']"

ouvrir_une_alarme="xpath=//*[@id=\"table-alarm\"]/tbody/tr[1]/td[3]"
nbreAlertes_dans_alarme="xpath=//*[@id=\"table-alarm\"]/tbody/tr[1]/td[9]"
nbrLignes_dans_InfosAlertes="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[3]/div[2]/div/table/tbody/tr"
survoler_statutAlarme="xpath = //*[@id=\"table-alarm\"]/tbody/tr[1]/td[11]/div[1]"
recuper_le_commentaire="xpath = //*[@id=\"table-alarm\"]/tbody/tr[1]/td[11]/div[2]/ul/li/a/span[1]"
precedent="xpath =/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[3]/div[1]/div[2]/div/a/span/span"

etat_frd = "xpath = /html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[1]/div[1]/div/div[1]/div[2]/ul/li/div/form/div/div[2]/span/div[2]/div[2]/span/div[1]/button/input"
etat_nonfrd = "xpath = /html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[1]/div[1]/div/div[1]/div[2]/ul/li/div/form/div/div[2]/span/div[2]/div[2]/span/div[2]/button/input"

lbl_nomAlarme="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[1]/th"
lbl_valeurAggregation="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[2]/th"
lbl_dateCreation="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[3]/th"
lbl_dateModification="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[4]/th"
lbl_statut="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[5]/th"
lbl_impactFinancier="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[6]/th"
lbl_nbrEnregistrements="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[7]/th"
lbl_tempsAnalyse="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[8]/th"
lbl_typeAggregation="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[9]/th"
lbl_assignation="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[10]/th"
lbl_reseau="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[11]/th"
lbl_detailsClient="xpath= /html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[1]/div[2]/div/div/div"
lbl_alertes="xpath= /html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[3]/div[2]/div"
lbl_historique="xpath= /html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[3]/div[1]/div[1]/div/div"
assigner_a_un_user="xpath=//*[@id=\"assigned-to\"]/option[10]"

verif_user_assigner="xpath= /html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[11]/td/span"
txt_searchAlarme="xpath=//*[@id=\"orange-navbar-collapse\"]/ul/li[9]/div/li[1]/div/form/input"
txt_search_filtre_regle="xpath=//input[@type='text']"
txt_nom_alarme="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[2]/div/div/div/div/table/tbody/tr[1]/td"

ligne_1_search_regle_TBSP="xpath=//form[@id='filtre']/div/div/angular2-multiselect/div/div[2]/div[3]/ul/span/li/label"
ligne_2_search_regle_TBSP="xpath=//form[@id='filtre']/div/div/angular2-multiselect/div/div[2]/div[3]/ul/span/li[2]/label"
onglet_CDR="id=tab-1-content-trigger"
titre_colonnes_CDR="//*[@id=\"tab-1-content\"]/div[2]/table/thead/tr"

#call date sur les infos CDR de lAlerte Alarme simbox TA_024
ligne_tableau_alarmeSimbox= "xpath=//table[@id='table-alarm']/tbody/tr/td[4]"
#survoler_Alerte= "xpath=//td[2]/span"
survoler_Alerte= "xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm-detail/div[3]/div[2]/div/table/tbody/tr/td[2]/span"
text_call_date= "xpath=//a/span[2]"
scroll_down= "xpath=//div[3]/div[2]/div"

######################################       WhiteLists Page Elements      ################################################
menu_whitelists= "xpath=//*[@id=\"orange-navbar-collapse\"]/ul/li[5]/a"
btn_creer_nouveau_whitelist= "xpath=//h2/button"
popup_creation_whitelist= "xpath=//ngb-modal-window/div/div"
lbl_Msisdn= "id=field_msisdn"
lbl_Observation= "id=field_observation"
btn_sauvegarderWL= "xpath=//div[3]/button[2]/span[2]/span"
lbl_rechercheWL= "id=currentSearch"
btn_rechercheWL= "xpath=//button[@type='submit']"
result_msisdn_recherche= "xpath=//td"
result_observation_recherche= "xpath=//td[4]"
result_statut_recherche= "xpath=//td[5]"

btn_charger_lot_whitelist= "//button[2]/span[2]/span"
popup_chargement_lot_WL= "name=editForm"
upload_fichier= "xpath=//input[@type='file']"
btn_activerWL= "xpath=//button[@id='whitelister']/span[2]/span"
btn_desactiverWL= "xpath=//button[@id='retirer']/span[2]/span"
result_dateCreation_recherche= "xpath=//td[2]"

txt_erreur_num_incorrect= "xpath=//div[3]/span/span"
txt_erreur_fichier_incorrect= "xpath=//p/span/span"

# Ousseynou
xpath_whitelist="//*[@id=\"orange-navbar-collapse\"]/ul/li[5]/a/span"
xpath_historique_whitelist="xpath=/html/body/jhi-main/div[2]/div/div/jhi-whitelist/div/h2/button[3]"
id_espaceRechercheNum="id=currentSearch"
xpath_charger_new_whlist="xpath=/html/body/jhi-main/div[2]/div/div/jhi-whitelist/div/h2/button[2]/span[2]/span"
xpath_boutton_creerNewWhitlist="xpath=/html/body/jhi-main/div[2]/div/div/jhi-whitelist/div/h2/button[1]/span[2]/span"
id_filtre_sur_statut="id=field_status"
xpath_msisdn="xpath=/html/body/jhi-main/div[2]/div/div/jhi-whitelist/div/div[2]/table/thead/tr/th[1]"
xpath_premiere_regle="xpath=//*[@id=\"regles_tab_info\"]/tbody/tr[1]/td[2]"

#Fallou
lbl_filters_dashboard="/html/body/jhi-main/div[2]/div/div/jhi-home/div/div/div/div/div[2]/div[1]/div/div/div/div/div[1]/h4"
flt_dateCreation_dahsboard="//*[@id=\"dropdownImpact\"]/span[2]"
flt_30_derniers_jrs_dashboard="xpath=/html/body/jhi-main/div[2]/div/div/jhi-home/div/div/div/div/div[2]/div[1]/div/div/div/div/div[2]/div[1]/div/div/div[1]/ul/li[4]/a/span"
txt_nbr_GEN="xpath=/html/body/jhi-main/div[2]/div/div/jhi-home/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div[2]/table/tbody/tr[1]/td[2]"
txt_nbr_INV="xpath=/html/body/jhi-main/div[2]/div/div/jhi-home/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div[2]/table/tbody/tr[1]/td[4]"
txt_nbr_PEN="xpath=/html/body/jhi-main/div[2]/div/div/jhi-home/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div[2]/table/tbody/tr[1]/td[5]"
txt_nbr_AVL="xpath=/html/body/jhi-main/div[2]/div/div/jhi-home/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div[2]/table/tbody/tr[1]/td[6]"
txt_nbr_NFR="xpath=/html/body/jhi-main/div[2]/div/div/jhi-home/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div[2]/table/tbody/tr[1]/td[7]"
txt_nbr_FRD="xpath=/html/body/jhi-main/div[2]/div/div/jhi-home/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div[2]/table/tbody/tr[1]/td[8]"
txt_TPC="xpath=/html/body/jhi-main/div[2]/div/div/jhi-home/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div[2]/table/tbody/tr[1]/td[9]/span"

flt_30_derniers_jrs="xpath=//*[@id=\"filtre\"]/div[1]/div[2]/div/div[1]/ul/li[4]/a/span"
nbr_total_results="xpath=/html/body/jhi-main/div[2]/div/div/jhi-alarm/div/div/div/div[2]/jhi-alarms-dropdown-filter/div/div[2]/span[2]"
nbrLignes_dans_alarmes="xpath=//*[@id=\"table-alarm\"]/tbody/tr"
flt_statut_simbox="xpath=//*[@id=\"filtre\"]/div[1]/div[8]/angular2-multiselect/div/div[1]/div/span"
#flt_sur_NEW="xpath=//form[@id='filtre']/div/div[8]/angular2-multiselect/div/div[2]/div[3]/ul/span/li/label"
search_statutAlarme="xpath=//*[@id=\"filtre\"]/div[1]/div[8]/angular2-multiselect/div/div[2]/div[3]/div[2]/input"
